# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e908b20d2c9179f2259cea115ca9b6d40b76ab0a523a9fbee7df4921c5f024aad2816eac1142b03eab7d243d9d6b273f4c4648383075a8b13747f9e829598caf

test:
  secret_key_base: 7ba798bafdd09df67d6afdab9e1292810cbf08bb83cfbb4c14aa77fa6b0bb8c8118a6bb7eb69e2e356b6b5bd788bc5ffa3c899c422fc1c4675d56076e8c4b981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
